### PR TITLE
Revert "Decrease the minSdk to 26"

### PR DESCRIPTION
**Pull request by Futsch1**
Reverts Futsch1/medTimer#389

Crashes in several tests are related to this change - the MinSDK will be kept at 28

### CODE REVIEW

**Comment by wh201906** [comment]
@Futsch1 Hi. I just found the failed test case might not be related to my PR #389. The CI also failed after the revert, and I found the culprit is these code

https://github.com/Futsch1/medTimer/blob/d5c6cd301472a9d0d4e925905635c1ce18781ee2/app/src/androidTest/java/com/futsch1/medtimer/ScreenshotsTest.java#L108-L111

I tried this test on commit 1e066f4c0de7b2b79e470a3f1cce56e883f844b5 and it looks like the `open_advanced_settings` is not clicked as expected. Instead, a date picker appears after executing `L108` and the test suite cannot switch to the `Analysis` tab.
Then I applied the changes in 1e066f4c0de7b2b79e470a3f1cce56e883f844b5 to 329d6bc17c2bb5c8bd8334a286f75689a7c2212d, and the test case passed. I guess you have fixed it in 329d6bc17c2bb5c8bd8334a286f75689a7c2212d.
Would you consider reverting this PR?

**Comment by Futsch1** [comment]
> @Futsch1 Hi. I just found the failed test case might not be related to my PR #389. The CI also failed after the revert, and I found the culprit is these code
> 
> https://github.com/Futsch1/medTimer/blob/d5c6cd301472a9d0d4e925905635c1ce18781ee2/app/src/androidTest/java/com/futsch1/medtimer/ScreenshotsTest.java#L108-L111
> 
> I tried this test on commit [1e066f4](https://github.com/Futsch1/medTimer/commit/1e066f4c0de7b2b79e470a3f1cce56e883f844b5) and it looks like the `open_advanced_settings` button is not clicked as expected. Instead, a date picker appears after executing `L108` and the test suite cannot switch to the `Analysis` tab. Then I applied the changes in [1e066f4](https://github.com/Futsch1/medTimer/commit/1e066f4c0de7b2b79e470a3f1cce56e883f844b5) to [329d6bc](https://github.com/Futsch1/medTimer/commit/329d6bc17c2bb5c8bd8334a286f75689a7c2212d), and the test case passed. I guess you have fixed it in [329d6bc](https://github.com/Futsch1/medTimer/commit/329d6bc17c2bb5c8bd8334a286f75689a7c2212d). Would you consider reverting this PR?

I would prefer if you rebase your branch on the current main and create another PR - the automated tests should run then.

I worked a lot on the stability of the tests, they worked well on my local PC, but in GitHub actions, where the emulation is a lot slower, it was quite hard to get them working.

**Comment by wh201906** [comment]
> I would prefer if you rebase your branch on the current main and create another PR

OK I will.

> I worked a lot on the stability of the tests, they worked well on my local PC, but in GitHub actions, where the emulation is a lot slower, it was quite hard to get them working.

Yeah the GitHub Action is flaky sometimes.

**Comment by wh201906** [comment]
New PR: #395

**Pull request merged**
