### PR TITLE
Add Inventory by Medecine

### PR DESCRIPTION
**Pull request by docjyJ**
- [x] Addition of the remaining quantity in the database.
- [ ] Decreed at each event.
- [ ] Personalize the number of medicine per event.
- [ ] Update translations.
- [ ] (Optional/discuss) Modify the UI of medicine.
- [ ] (Optional/discuss) Use set of colors instead of picker.
- [ ] (Optional/discuss) Add icon, pill, capsule, syrup, etc.

### CODE REVIEW

**Comment by Futsch1** [comment]
Hey Jean-Yves, thanks for your contribution and your willingness to improve the app. I have so far refrained from working on the inventory because the amount is (and it seems to make sense this way) a string and not a number. So you might have to check if the amount is actually a number in order to be able to use inventories.

So it's all a bit complicated and would also make the UI more complex. But if you find a nice solution to these issues I would be perfectly willing to add the feature (and the others planned by you) to the app.

**Comment by docjyJ** [comment]
Hi,

Right now, I don't have enough time to work.

I still use your application is it is still as great!

It is true that this functionalty is commplex because of string.

Thank you for your work. :heart:

**Comment by Omarwk** [comment]
Maybe adding the image of the med would help also the people who vision challenged

**Comment by docjyJ** [comment]
Yes, I don't have enough time to work on it. Maybe work on a feature request.

**Pull request closed without merging**
